/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 islandModel.gltf 
*/

import React, { useRef } from 'react'
import { useLoader } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

export function Model({ boxHeight, ...props }) {
  const gltf = useLoader(GLTFLoader, '/islandModel.gltf');
  const { nodes } = gltf;


  return (
    <group {...props} dispose={null}>
      <group position={[4.3, -2.6, -2]} scale={[-0.011, 0.011, 0.011]}>
        <mesh geometry={nodes.mesh_1.geometry} material={nodes.mesh_1.material} position={[0, 0, 114.262]} />
        <mesh geometry={nodes.mesh_2.geometry} material={nodes.mesh_2.material} position={[0, 0, 114.261]} />
        <mesh geometry={nodes.mesh_3.geometry} material={nodes.mesh_3.material} position={[0, 0, 114.263]} />
        <mesh geometry={nodes.mesh_4.geometry} material={nodes.mesh_4.material} position={[0, 0, 114.263]} />
        <mesh geometry={nodes.mesh_5.geometry} material={nodes.mesh_5.material} position={[0, 0, 114.263]} />
        <mesh geometry={nodes.mesh_6.geometry} material={nodes.mesh_6.material} position={[0, 0, 114.263]} />
        <mesh geometry={nodes.mesh_7.geometry} material={nodes.mesh_7.material} position={[0, 0, 114.263]} />
        <mesh geometry={nodes.mesh_8.geometry} material={nodes.mesh_8.material} position={[0, 0, 114.261]} />
        <mesh geometry={nodes.mesh_9.geometry} material={nodes.mesh_9.material} position={[0, 0, 114.261]} />
        <mesh geometry={nodes.mesh_10.geometry} material={nodes.mesh_10.material} position={[0, 0, 114.263]} />
        <mesh geometry={nodes.mesh_11.geometry} material={nodes.mesh_11.material} position={[0, 0, 114.264]} />
        <mesh geometry={nodes.mesh_12.geometry} material={nodes.mesh_12.material} position={[0, 0, 114.263]} />
        <mesh geometry={nodes.mesh_13.geometry} material={nodes.mesh_13.material} position={[0, 0, 114.262]} />
        <mesh geometry={nodes.mesh_14.geometry} material={nodes.mesh_14.material} position={[0, 0, 114.263]} />
        <mesh geometry={nodes.mesh_15.geometry} material={nodes.mesh_15.material} position={[0, 0, 114.263]} />
        <group position={[0, 0, 114.263]}>
          <mesh geometry={nodes.mesh_16.geometry} material={nodes.mesh_16.material} />
          <mesh geometry={nodes.mesh_17.geometry} material={nodes.mesh_17.material} />
        </group>
        <mesh geometry={nodes.mesh_18.geometry} material={nodes.mesh_18.material} position={[0, 0, 114.263]} />
        <mesh geometry={nodes.mesh_19.geometry} material={nodes.mesh_19.material} position={[0, 0, 114.189]} />
        <mesh geometry={nodes.mesh_20.geometry} material={nodes.mesh_20.material} position={[0, 0, 114.243]} />
        <mesh geometry={nodes.mesh_21.geometry} material={nodes.mesh_21.material} position={[0, 0, 139.836]} />
        <mesh geometry={nodes.mesh_22.geometry} material={nodes.mesh_22.material} position={[0, 0, 139.836]} />
        <mesh geometry={nodes.mesh_23.geometry} material={nodes.mesh_23.material} position={[0, 0, 139.836]} />
        <mesh geometry={nodes.mesh_24.geometry} material={nodes.mesh_24.material} position={[0, 0, 139.836]} />
        <mesh geometry={nodes.mesh_25.geometry} material={nodes.mesh_25.material} position={[0, 0, 139.836]} />
        <mesh geometry={nodes.mesh_26.geometry} material={nodes.mesh_26.material} position={[0, 0, 139.836]} />
        <mesh geometry={nodes.mesh_27.geometry} material={nodes.mesh_27.material} position={[0, 0, 189.16]} />
        <group position={[0, 0, 189.161]}>
          <mesh geometry={nodes.mesh_28.geometry} material={nodes.mesh_28.material} scale={[1, 1, 0.864]} />
        </group>
        <mesh geometry={nodes.mesh_29.geometry} material={nodes.mesh_29.material} position={[0, 0, 189.162]} />
        <mesh geometry={nodes.mesh_30.geometry} material={nodes.mesh_30.material} position={[0, 0, 189.163]} />
        <mesh geometry={nodes.mesh_31.geometry} material={nodes.mesh_31.material} position={[0, 0, 189.16]} />
        <group position={[0, 0, 189.162]}>
          <mesh geometry={nodes.mesh_32.geometry} material={nodes.mesh_32.material} />
          <mesh geometry={nodes.mesh_33.geometry} material={nodes.mesh_33.material} />
        </group>
        <mesh geometry={nodes.mesh_34.geometry} material={nodes.mesh_34.material} position={[0, 0, 189.162]} />
        <mesh geometry={nodes.mesh_35.geometry} material={nodes.mesh_35.material} position={[0, 0, 189.162]} />
        <mesh geometry={nodes.mesh_36.geometry} material={nodes.mesh_36.material} position={[0, 0, 189.162]} />
        <mesh geometry={nodes.mesh_37.geometry} material={nodes.mesh_37.material} position={[0, 0, 189.162]} />
        <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/islandModel.gltf')
